// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDdDAbBSib3IXtaSY93jMbfmpLICURoUM',
    appId: '1:447567256711:web:5f8ad9bcba3a105cdf2c22',
    messagingSenderId: '447567256711',
    projectId: 'barberku-notif',
    authDomain: 'barberku-notif.firebaseapp.com',
    storageBucket: 'barberku-notif.firebasestorage.app',
    measurementId: 'G-GMMP3Y4LWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpUIQzNdvCe8itIRZr9TViXqfh2yGXDV0',
    appId: '1:447567256711:android:f6d086df4dcc060fdf2c22',
    messagingSenderId: '447567256711',
    projectId: 'barberku-notif',
    storageBucket: 'barberku-notif.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe4ITKhK3WLyBPgJQkCqjzzl2IywpuoB4',
    appId: '1:447567256711:ios:956c374382b1378adf2c22',
    messagingSenderId: '447567256711',
    projectId: 'barberku-notif',
    storageBucket: 'barberku-notif.firebasestorage.app',
    iosBundleId: 'com.barberku.barberkuApp',
  );
}
